#!/usr/bin/env bash

DOTFILES_DIR=$HOME/dotfiles
OUTPUT_FILE=$DOTFILES_DIR/Brewfile

if [ ! -d $DOTFILES_DIR ]; then
  echo "Error: Dotfiles directory not found at $DOTFILES_DIR."
  exit 1
fi

echo "Updating $OUTPUT_FILE..."

brew bundle dump --force --file=$OUTPUT_FILE
