[pyprland]
plugins = ["scratchpads"]

[scratchpads.pwvucontrol]
animation = "fromTop"
command = "pwvucontrol"
class = "com.saivert.pwvucontrol"
size = "50% 80%"
workspace = "special:scratch_pwvucontrol"
allow_special_workspaces = true
unfocus = "hide"
lazy = true

[scratchpads.term]
command = "ghostty"
animation = "fromRight"
class = "com.mitchellh.ghostty"
workspace = "special:scratch_term"
allow_special_workspaces = true
unfocus = "hide"
lazy = true

